[package]
name = "hspee/steal-a-meme"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2.0.3"
ZonePlus = "mattschrubb/zoneplus@3.2.0"
Replica = "azutreo/replica@1.0.1"

[server-dependencies]
cmdr = "evaera/cmdr@1.12.0"